name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.ref != 'refs/heads/master'

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}
      - run: npm -v
      - run: npm ci
      - run: npm run package

      # Run the tests
      - run: cd e2e
      - run: npm run build
      - run: npm run test